import React, { useState } from "react";
import axios from "axios";

const DalleForm = () => {
    const [description, setDescription] = useState("");
    const [imageUrl, setImageUrl] = useState("");
    const [loading, setLoading] = useState(false);

    const handleGenerateImage = async () => {
        setLoading(true);
        try {
            const response = await axios.post(
                "https://api.openai.com/v1/images/generations",
                {
                    prompt: description, // La descripción ingresada por el usuario
                    n: 1, // Número de imágenes que quieres generar
                    size: "1024x1024", // Tamaño de la imagen (puedes cambiarlo)
                },
                {
                    headers: {
                        Authorization: `Bearer YOUR_API_KEY`, // Sustituye con tu clave API de OpenAI
                        "Content-Type": "application/json",
                    },
                }
            );

            // Guardamos la URL de la imagen generada en el estado
            const imageUrl = response.data.data[0].url;
            setImageUrl(imageUrl);
        } catch (error) {
            console.error("Error generating image:", error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="form-wrapper mt-5">
            <div className="mb-3 w-50">
                <label className="form-label">Image Description</label>
                <input
                    type="text"
                    className="form-control"
                    placeholder="Describe the image"
                    onChange={(e) => setDescription(e.target.value)}
                    value={description}
                />
            </div>
            <div>
                <button
                    className="btn btn-primary mb-3"
                    onClick={handleGenerateImage}
                    disabled={loading || !description}
                >
                    {loading ? "Generating..." : "Generate Image"}
                </button>
            </div>

            {imageUrl && (
                <div className="image-container">
                    <h4>Generated Image:</h4>
                    <img src={imageUrl} alt="Generated by DALL·E" style={{ maxWidth: "100%" }} />
                </div>
            )}
        </div>
    );
};

export default DalleForm;
